name: "_shared"
description: "Checkout a GitHub repository into a folder"

runs:
  using: "composite"
  steps:
    - name: Validate required env
      shell: bash
      run: |
        set -euo pipefail
        if [[ -z "${SHARED_REPO_NAME:-}" ]]; then
          echo "SHARED_REPO_NAME env var is required (e.g. 'org/repo')." >&2
          exit 1
        fi

    - name: Pull repository (default branch)
      if: ${{ env.SHARED_REPO_BRANCH == '' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SHARED_REPO_NAME }}
        token: ${{ env.GITHUB_TOKEN || github.token }}
        path: ${{ env.SHARED_FOLDER || './shared' }}

    - name: Pull repository (explicit ref)
      if: ${{ env.SHARED_REPO_BRANCH != '' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SHARED_REPO_NAME }}
        ref: ${{ env.SHARED_REPO_BRANCH }}
        token: ${{ env.GITHUB_TOKEN || github.token }}
        path: ${{ env.SHARED_FOLDER || './shared' }}
